export default [
    {ignores: ['dist', 'node_modules']},
    {
        files: ['**/*.{js,jsx}'],
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: 'module',
            globals: {
                window: 'readonly',
                document: 'readonly',
                console: 'readonly',
                navigator: 'readonly',
                localStorage: 'readonly',
                fetch: 'readonly',
                RTCPeerConnection: 'readonly',
                RTCSessionDescription: 'readonly',
                RTCIceCandidate: 'readonly',
                FormData: 'readonly',
                FileReader: 'readonly',
                HTMLInputElement: 'readonly',
                HTMLTextAreaElement: 'readonly',
                HTMLVideoElement: 'readonly',
                HTMLImageElement: 'readonly',
                URL: 'readonly',
                Blob: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                import: 'readonly',
                CustomEvent: 'readonly',
                Event: 'readonly',
                EventTarget: 'readonly',
                HTMLElement: 'readonly',
                React: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': 'off',
            'no-empty': 'off',
            'no-useless-catch': 'off',
        },
    },
];
